// front/react/src/pages/ScheduledTasks.js
import React, {Component} from 'react';
import Card from '@material-ui/core/Card';
import Icon from '@material-ui/core/Icon';
import PropTypes from "prop-types";
import {withStyles} from "@material-ui/core";
import {FormattedMessage, injectIntl, intlShape} from "react-intl";
import TableCell from '@material-ui/core/TableCell';
import TableRow from '@material-ui/core/TableRow';
import Input from '@material-ui/core/Input/Input';
import InputAdornment from '@material-ui/core/InputAdornment';

import api from '../services/api';
import logger from '../services/logger';
import utils from '../services/utils';
import Raw from '../components/Raw';
import ColoredButton from "../components/ColoredButton";
import ButtonFilter from "../components/ButtonFilter";
import {openSnackbar} from "../components/Notifier";
import Typography from "@material-ui/core/Typography/Typography";
import CardHeader from "../components/CardHeader";
import CardTable from "../components/CardTable";
import CardBody from "../components/CardBody";
import Grid from "@material-ui/core/Grid/Grid";

class ScheduledTasks extends Component {

    state = {
        source: null,
        loading: true,
        columns: [
            {id: 'name', sortable: true, i18n: 'common.name'},
            {id: 'type', sortable: true, i18n: 'common.type'},
            {id: 'trigger', sortable: true, i18n: 'tasks.trigger'},
            {id: 'details', sortable: false, i18n: 'common.details'},
        ],
        data: [],
        types: [],
        typeFilters: [],
        search: ''
    };

    componentDidMount() {
        this.refresh();
    };

    refresh() {
        this.setState({loading: true});
        api.scheduledtasks().then(response => {
            let types = [];
            let data = [];
            for (const type of Object.keys(response.data)) {
                utils.putIfAbsent(types, type.toUpperCase());
                for (const item of response.data[type]) {
                    data.push({
                        name: item.runnable ? item.runnable.target : 'unknown',
                        type: type.toUpperCase(),
                        original: item
                    });
                }
            }
            this.setState({
                source: response.data,
                data,
                types
            });
        }).catch((e) => {
            logger.error("Error while loading scheduled tasks", e);
            openSnackbar(<FormattedMessage id="error.get.tasks"/>, 'error');
        }).finally(() => {
            this.setState({loading: false});
        })
    };

    filter = (list) => {
        return list.filter((value) => {
            return utils.search(this.state.search, value, ['name', 'type']) &&
                utils.inFilter(this.state.typeFilters, value.type);
        })
    };

    searchPlaceHolder() {
        return this.props.intl.formatMessage({id: 'common.filter'});
    };

    handleFilter = (value, onSelect) => {
        this.setState({typeFilters: utils.buildFilter(this.state.typeFilters, value, onSelect)});
    };

    handleChange = (event) => {
        this.setState({
            search: event.target.value,
        });
    };

    render() {
        const {source, data, loading, columns, types} = this.state;

        return (
            <div>
                <Card>
                    <CardHeader source={source} url="/scheduledtasks" refresh={() => this.refresh()}
                                title={<FormattedMessage id={"tasks.title"}/>}/>
                    <CardBody loading={loading}>
                        <div className={"filters"}>
                            <Typography component={"span"}>
                                <Grid container direction="row" justify="space-between" alignItems="center">
                                    <Grid item>
                                        <FormattedMessage id="filter.types"/>
                                        {types.map((type, idx) => {
                                            return (
                                                <ButtonFilter
                                                    key={idx} text={type} color={utils.color(type)}
                                                    onSelect={() => this.handleFilter(type, true)}
                                                    onDelete={() => this.handleFilter(type, false)}
                                                />
                                            );
                                        })}
                                    </Grid>
                                    <Grid item xs={12} sm>
                                        <Input id="search" type={"text"} className={"full-width"}
                                               value={this.state.search} placeholder={this.searchPlaceHolder()}
                                               onChange={this.handleChange}
                                               endAdornment={
                                                   <InputAdornment position="end">
                                                       <Icon>search</Icon>
                                                   </InputAdornment>
                                               }
                                        />
                                    </Grid>
                                </Grid>
                            </Typography>
                        </div>
                        {data &&
                        <CardTable
                            data={data} columns={columns} customFilter={this.filter}
                            initialOrder={"asc"} initialOrderBy={"name"}
                            row={(row, idx) => {
                                return (
                                    <TableRow key={idx}>
                                        <TableCell>{row.name}</TableCell>
                                        <TableCell>
                                            <ColoredButton size={"s"}
                                                           color={utils.color(row.type)}
                                                           text={row.type}>
                                            </ColoredButton>
                                        </TableCell>
                                        <TableCell>
                                            {row.type === 'CRON' ?
                                                <Typography component={"span"}>
                                                    <FormattedMessage id="tasks.expression"/>
                                                    <ColoredButton variant={"contained"} color={utils.color('info')}>
                                                        {row.original.expression}
                                                    </ColoredButton>
                                                </Typography> :
                                                <Typography component={"span"}>
                                                    <FormattedMessage id="tasks.initial-delay"/>
                                                    <ColoredButton variant={"contained"} color={utils.color('info')}>
                                                        {row.original.initialDelay}
                                                    </ColoredButton>
                                                    <FormattedMessage id="tasks.interval"/>
                                                    <ColoredButton variant={"contained"} color={utils.color('info')}>
                                                        {row.original.interval}
                                                    </ColoredButton>
                                                </Typography>
                                            }
                                        </TableCell>
                                        <TableCell><Raw raw={row.original}/></TableCell>
                                    </TableRow>
                                )
                            }}/>
                        }
                    </CardBody>
                </Card>
            </div>
        );
    }
}

ScheduledTasks.propTypes = {
    classes: PropTypes.object.isRequired,
    intl: intlShape.isRequired
};

export default injectIntl(withStyles({...utils.defaultCardContentStyle})(ScheduledTasks));

// front/vue/src/views/ScheduledTasks.vue
<template>
    <actuator-card :source="source" :refresh="refresh" url="/scheduledtasks">
        <template slot="title">
            <span v-t="'tasks.title'"></span>
        </template>
        <template slot="content">

            <v-layout justify-space-between class="filters">
                <div>
                    <span v-t="'filter.types'"></span>
                    <button-filter v-for="type in types" :key="type" :name="type"
                                   :on-select="activate.bind(this, typeFilters, type)"
                                   :on-remove="deactivate.bind(this, typeFilters, type)"
                                   :color="color(type)">

                    </button-filter>
                </div>

                <v-text-field class="search-field" v-model="search" append-icon="search" :label="$t('common.filter')"
                              single-line
                              hide-details></v-text-field>
            </v-layout>

            <v-data-table :headers="headers" :items="rows" :search="search" :loading="loading"
                          :pagination.sync="pagination" :rows-per-page-items="itemsPerPage">
                <template slot="items" slot-scope="props">
                    <td>{{ props.item.name }}</td>
                    <td>
                        <v-btn small round :color="color(props.item.type)">{{ props.item.type }}</v-btn>
                    </td>
                    <td>
            <span v-if="props.item.type === 'CRON'">
              <span v-t="'tasks.expression'">Expression: </span>
              <v-btn small color="info" class="badge badge-info">{{props.item.original.expression}}</v-btn>
            </span>
                        <span v-else>
              <span v-t="'tasks.initial-delay'">Initial delay: </span>
              <v-btn small color="info" class="badge badge-info">{{props.item.original.initialDelay}}</v-btn>
              <span v-t="'tasks.interval'">Interval: </span>
              <v-btn small color="info" class="badge badge-info">{{props.item.original.interval}}</v-btn>
            </span>
                    </td>
                    <td>
                        <raw :raw="props.item.original"></raw>
                    </td>
                </template>
            </v-data-table>
        </template>
    </actuator-card>
</template>

<script>
    import Abstract from './Abstract.vue';

    export default {
        extends: Abstract,
        data() {
            return {
                errorMessage: this.$t('error.get.tasks'),
                types: [],
                typeFilters: [],
                pagination: {sortBy: 'timestamp', descending: true, rowsPerPage: 10}
            };
        },
        methods: {
            internalRefresh() {
                return this.$api.scheduledtasks().then((response) => {
                    this.source = response.data;
                    this.types = [];
                    this.tableData = [];
                    for (const type of Object.keys(response.data)) {
                        this.putIfAbsent(this.types, type.toUpperCase());
                        for (const item of response.data[type]) {
                            this.tableData.push({
                                name: item.runnable ? item.runnable.target : 'unknown',
                                type: type.toUpperCase(),
                                original: item
                            });
                        }
                    }
                });
            }
        },
        computed: {
            rows() {
                if (this.typeFilters.length === 0) {
                    return this.tableData;
                }
                this.pagination.page = 1;
                return this.tableData.filter((value) => this.typeFilters.indexOf(value.type) > -1);
            },
            headers() {
                return [
                    {text: this.$t('common.name'), value: 'name'},
                    {text: this.$t('common.type'), value: 'type'},
                    {text: this.$t('tasks.trigger'), value: 'trigger'},
                    {text: this.$t('common.details'), value: 'none'}
                ];
            }
        }
    };
</script>
