// front/react/src/pages/ThreadDump.js
import React, {Component} from 'react';
import Card from '@material-ui/core/Card';
import Icon from '@material-ui/core/Icon';
import PropTypes from "prop-types";
import {withStyles} from "@material-ui/core";
import {FormattedMessage, injectIntl, intlShape} from "react-intl";
import TableCell from '@material-ui/core/TableCell';
import TableRow from '@material-ui/core/TableRow';
import Input from '@material-ui/core/Input/Input';
import InputAdornment from '@material-ui/core/InputAdornment';

import api from '../services/api';
import logger from '../services/logger';
import utils from '../services/utils';
import Raw from '../components/Raw';
import ColoredButton from "../components/ColoredButton";
import ButtonFilter from "../components/ButtonFilter";
import {openSnackbar} from "../components/Notifier";
import Typography from "@material-ui/core/Typography/Typography";
import CardHeader from "../components/CardHeader";
import CardTable from "../components/CardTable";
import CardBody from "../components/CardBody";
import Grid from "@material-ui/core/Grid/Grid";

class ThreadDump extends Component {

    state = {
        source: null,
        states: [],
        loading: true,
        columns: [
            {id: 'threadId', sortable: true, i18n: 'dump.thread-id'},
            {id: 'threadName', sortable: true, i18n: 'dump.thread-name'},
            {id: 'threadState', sortable: true, i18n: 'dump.thread-state'},
            {id: 'details', sortable: false, i18n: 'common.details'},
        ],
        stateFilters: [],
        search: ''
    };

    componentDidMount() {
        this.refresh();
    };

    refresh() {
        this.setState({loading: true});
        api.threaddump().then(response => {
            let states = [];
            for (const thread of response.data.threads) {
                utils.putIfAbsent(states, thread.threadState);
            }
            this.setState({
                source: response.data,
                states
            })
        }).catch((e) => {
            logger.error("Error while loading thread dumps", e);
            openSnackbar(<FormattedMessage id="error.get.dump"/>, 'error');
        }).finally(() => {
            this.setState({loading: false});
        })
    };

    filter = (list) => {
        return list.filter((value) => {
            return utils.search(this.state.search, value, ['threadId', 'threadName', 'threadState']) &&
                utils.inFilter(this.state.stateFilters, value.threadState);
        })
    };

    searchPlaceHolder() {
        return this.props.intl.formatMessage({id: 'common.filter'});
    };

    handleFilter = (value, onSelect) => {
        this.setState({stateFilters: utils.buildFilter(this.state.stateFilters, value, onSelect)});
    };

    handleChange = (event) => {
        this.setState({
            search: event.target.value,
        });
    };

    render() {
        const {source, loading, columns, states} = this.state;

        return (
            <div>
                <Card>
                    <CardHeader source={source} url="/threaddump" refresh={() => this.refresh()}
                                title={<FormattedMessage id={"dump.title"}/>}/>
                    <CardBody loading={loading}>
                        <div className={"filters"}>
                            <Typography component={"span"}>
                                <Grid container direction="row" justify="space-between" alignItems="center">
                                    <Grid item>
                                        <FormattedMessage id="filter.state"/>
                                        {states.map((state, idx) => {
                                            return (
                                                <ButtonFilter
                                                    key={idx} text={state} color={utils.color(state)}
                                                    onSelect={() => this.handleFilter(state, true)}
                                                    onDelete={() => this.handleFilter(state, false)}
                                                />
                                            );
                                        })}
                                    </Grid>
                                    <Grid item xs={12} sm>
                                        <Input id="search" type={"text"} className={"full-width"}
                                               value={this.state.search} placeholder={this.searchPlaceHolder()}
                                               onChange={this.handleChange}
                                               endAdornment={
                                                   <InputAdornment position="end">
                                                       <Icon>search</Icon>
                                                   </InputAdornment>
                                               }
                                        />
                                    </Grid>
                                </Grid>
                            </Typography>
                        </div>
                        {source &&
                        <CardTable
                            data={source.threads} columns={columns} customFilter={this.filter}
                            initialOrder={"asc"} initialOrderBy={"threadId"}
                            row={(row, idx) => {
                                return (
                                    <TableRow key={idx}>
                                        <TableCell>{row.threadId}</TableCell>
                                        <TableCell>{row.threadName}</TableCell>
                                        <TableCell>
                                            <ColoredButton size={"s"}
                                                           color={utils.color(row.threadState)}
                                                           text={row.threadState}>
                                            </ColoredButton>
                                        </TableCell>
                                        <TableCell><Raw raw={row}/></TableCell>
                                    </TableRow>
                                )
                            }}/>
                        }
                    </CardBody>
                </Card>
            </div>
        );
    }
}

ThreadDump.propTypes = {
    classes: PropTypes.object.isRequired,
    intl: intlShape.isRequired
};

export default injectIntl(withStyles({...utils.defaultCardContentStyle})(ThreadDump));

// front/vue/src/views/ThreadDump.vue
<template>
    <actuator-card :source="source" :refresh="refresh" url="/threaddump">
        <template slot="title">
            <span v-t="'dump.title'"></span>
        </template>
        <template slot="content">

            <v-layout justify-space-between class="filters">
                <div>
                    <span v-t="'filter.state'"></span>
                    <button-filter v-for="state in states" :key="state" :name="state"
                                   :on-select="activate.bind(this, stateFilters, state)"
                                   :on-remove="deactivate.bind(this, stateFilters, state)"
                                   :color="color(state)">

                    </button-filter>
                </div>

                <v-text-field class="search-field" v-model="search" append-icon="search" :label="$t('common.filter')"
                              single-line hide-details>

                </v-text-field>
            </v-layout>

            <v-data-table :headers="headers" :items="rows" :search="search" :loading="loading"
                          :pagination.sync="pagination" :rows-per-page-items="itemsPerPage">
                <template slot="items" slot-scope="props">
                    <td>{{ props.item.threadId }}</td>
                    <td>{{ props.item.threadName }}</td>
                    <td>
                        <v-btn small round :color="color(props.item.threadState)">{{ props.item.threadState }}</v-btn>
                    </td>
                    <td>
                        <raw :raw="props.item"></raw>
                    </td>
                </template>
            </v-data-table>
        </template>
    </actuator-card>
</template>

<script>
    import Abstract from './Abstract.vue';

    export default {
        extends: Abstract,
        data() {
            return {
                errorMessage: this.$t('error.get.dump'),
                states: [],
                stateFilters: [],
                pagination: {rowsPerPage: 10}
            };
        },
        methods: {
            internalRefresh() {
                return this.$api.threaddump().then((response) => {
                    this.source = response.data;
                    this.tableData = response.data.threads;
                    this.states = [];
                    for (const thread of response.data.threads) {
                        this.putIfAbsent(this.states, thread.threadState);
                    }
                });
            }
        },
        computed: {
            rows() {
                if (this.stateFilters.length === 0) {
                    return this.tableData;
                }
                this.pagination.page = 1;
                return this.tableData.filter((value) => this.stateFilters.indexOf(value.threadState) > -1);
            },
            headers() {
                return [
                    {text: this.$t('dump.thread-id'), value: 'threadId'},
                    {text: this.$t('dump.thread-name'), value: 'threadName'},
                    {text: this.$t('dump.thread-state'), value: 'threadState'},
                    {text: this.$t('common.details'), value: 'none'}
                ];
            }
        }
    };
</script>
