// front/react/src/pages/Conditions.js
import React, {Component} from 'react';
import Card from '@material-ui/core/Card';
import Icon from '@material-ui/core/Icon';
import PropTypes from "prop-types";
import {withStyles} from "@material-ui/core";
import {FormattedMessage, injectIntl, intlShape} from "react-intl";
import TableCell from '@material-ui/core/TableCell';
import TableRow from '@material-ui/core/TableRow';
import Input from '@material-ui/core/Input/Input';
import InputAdornment from '@material-ui/core/InputAdornment';

import api from '../services/api';
import logger from '../services/logger';
import utils from '../services/utils';
import Raw from '../components/Raw';
import ColoredButton from "../components/ColoredButton";
import ButtonFilter from "../components/ButtonFilter";
import {openSnackbar} from "../components/Notifier";
import Typography from "@material-ui/core/Typography/Typography";
import CardHeader from "../components/CardHeader";
import CardTable from "../components/CardTable";
import CardBody from "../components/CardBody";
import Grid from "@material-ui/core/Grid/Grid";
import Tabs from "@material-ui/core/Tabs/Tabs";
import Tab from "@material-ui/core/Tab/Tab";

function map(matches, type) {
    return Object.keys(matches).map((key) => ({
        name: key,
        type,
        original: matches[key]
    }));
}

class Conditions extends Component {

    state = {
        source: null,
        types: ['POSITIVE', 'NEGATIVE', 'UNCONDITIONAL'],
        loading: true,
        columns: [
            {id: 'name', sortable: true, i18n: 'beans.name'},
            {id: 'type', sortable: true, i18n: 'common.type'},
            {id: 'details', sortable: false, i18n: 'common.details'},
        ],
        typeFilters: [],
        search: '',
        tableDataList: {},
        tab: 0
    };

    componentDidMount() {
        this.refresh();
    };

    refresh() {
        this.setState({loading: true});
        api.conditions().then(response => {
            let tableDataList = [];
            for (const contextName in response.data.contexts) {
                if (response.data.contexts.hasOwnProperty(contextName)) {
                    tableDataList[contextName] = {
                        name: contextName,
                        parent: response.data.contexts[contextName].parentId,
                        data: []
                    };
                    tableDataList[contextName].data = tableDataList[contextName].data.concat(
                        map(response.data.contexts[contextName].positiveMatches, 'POSITIVE'));
                    tableDataList[contextName].data = tableDataList[contextName].data.concat(
                        map(response.data.contexts[contextName].negativeMatches, 'NEGATIVE'));
                    for (const idx in response.data.contexts[contextName].unconditionalClasses) {
                        if (response.data.contexts[contextName].unconditionalClasses.hasOwnProperty(idx)) {
                            tableDataList[contextName].data.push({
                                name: response.data.contexts[contextName].unconditionalClasses[idx],
                                type: 'UNCONDITIONAL'
                            });
                        }
                    }
                }
            }
            this.setState({source: response.data, tableDataList});
        }).catch((e) => {
            logger.error("Error while loading conditions", e);
            openSnackbar(<FormattedMessage id="error.get.conditions"/>, 'error');
        }).finally(() => {
            this.setState({loading: false});
        })
    };

    filter = (list) => {
        return list.filter((value) => {
            return utils.search(this.state.search, value, ['name']) &&
                utils.inFilter(this.state.typeFilters, value.type);
        })
    };

    searchPlaceHolder() {
        return this.props.intl.formatMessage({id: 'common.filter'});
    };

    handleFilter = (value, onSelect) => {
        this.setState({typeFilters: utils.buildFilter(this.state.typeFilters, value, onSelect)});
    };

    handleChange = (event) => {
        this.setState({search: event.target.value,});
    };

    handleTabChange = (event, value) => {
        this.setState({tab: value});
    };


    render() {
        const {source, loading, columns, types, search, tableDataList, tab} = this.state;

        return (
            <div>
                <Card>
                    <CardHeader source={source} url="/conditions" refresh={() => this.refresh()}
                                title={<FormattedMessage id={"conditions.title"}/>}/>
                    <CardBody loading={loading}>
                        {tableDataList && tableDataList[Object.keys(tableDataList)[tab]] &&
                        <div>
                            <Tabs value={tab} onChange={this.handleTabChange} indicatorColor="primary"
                                  textColor="primary">

                                {Object.keys(tableDataList).map((name) => {
                                    return (
                                        <Tab key={name}
                                             label={<span><FormattedMessage id="common.context"/> : {name}</span>}/>
                                    );
                                })}
                            </Tabs>
                            <div className={"filters"} style={{marginTop: '10px'}}>
                                <Typography component={"span"}>
                                    <Grid container direction="row" justify="space-between" alignItems="center">
                                        <Grid item>
                                            <FormattedMessage id="filter.types"/>
                                            {types.map((type, idx) => {
                                                return (
                                                    <ButtonFilter
                                                        key={idx} text={type} color={utils.color(type)}
                                                        onSelect={() => this.handleFilter(type, true)}
                                                        onDelete={() => this.handleFilter(type, false)}
                                                    />
                                                );
                                            })}
                                        </Grid>
                                        <Grid item xs={12} sm>
                                            <Input id="search" type={"text"} className={"full-width"}
                                                   value={search} placeholder={this.searchPlaceHolder()}
                                                   onChange={this.handleChange}
                                                   endAdornment={
                                                       <InputAdornment position="end">
                                                           <Icon>search</Icon>
                                                       </InputAdornment>
                                                   }
                                            />
                                        </Grid>
                                    </Grid>
                                </Typography>
                            </div>
                            <CardTable
                                data={tableDataList[Object.keys(tableDataList)[tab]].data} columns={columns}
                                customFilter={this.filter}
                                initialOrder={"asc"} initialOrderBy={"name"}
                                row={(row, idx) => {
                                    return (
                                        <TableRow key={idx}>
                                            <TableCell>{row.name}</TableCell>
                                            <TableCell>
                                                <ColoredButton size={"s"} color={utils.color(row.type)}
                                                               text={row.type}>
                                                </ColoredButton>
                                            </TableCell>
                                            <TableCell><Raw raw={row}/></TableCell>
                                        </TableRow>
                                    )
                                }}/>
                        </div>
                        }
                    </CardBody>
                </Card>
            </div>
        );
    }
}

Conditions.propTypes = {
    classes: PropTypes.object.isRequired,
    intl: intlShape.isRequired
};

export default injectIntl(withStyles({...utils.defaultCardContentStyle})(Conditions));

// front/vue/src/pages/actuator/Conditions.vue
<template>
    <div class="card card-page">
        <div class="card-header d-flex">
            <div><span v-t="'conditions.title'"></span></div>
            <div class="ml-auto">
                <raw :raw="source"></raw>
                <fa class="pointer" icon="sync" @click="!loading && refresh()" :spin="loading" v-b-tooltip.hover
                    :title="$t('refresh.data')"/>
            </div>
        </div>
        <div class="card-body">
            <spinner :show="loading"></spinner>
            <div v-if="!loading">
                <b-tabs pills v-model="tabIndex">
                    <b-tab :title="tableData.name" :key="tableData.name" v-for="tableData of tableDataList">
                        <p v-if="tableData.parent" class="alert alert-info">
                            <span v-t="'common.parent-context'"></span>
                            <span class="tab-link" @click="tab(tableData.parent)">{{tableData.parent}}</span>
                        </p>
                        <p class="alert alert-primary">
                            <span v-t="'filter.types'"></span>
                            <span class="space badge pointer" @click="filter(tableData.name, 'all')"
                                  v-bind:class="badge('all')"><span v-t="'common.all'"></span></span>
                            <span class="space badge pointer" @click="filter(tableData.name, 'POSITIVE')"
                                  v-bind:class="badge('POSITIVE')">POSITIVE</span>
                            <span class="space badge pointer" @click="filter(tableData.name, 'NEGATIVE')"
                                  v-bind:class="badge('NEGATIVE')">NEGATIVE</span>
                            <span class="space badge pointer" @click="filter(tableData.name, 'UNCONDITIONAL')"
                                  v-bind:class="badge('UNCONDITIONAL')">UNCONDITIONAL</span>
                        </p>
                        <v-client-table :ref="tableData.name" :data="tableData.data" :columns="columns"
                                        :options="options(tableData.name)">
                            <div slot="type" slot-scope="props">
                                <span class="badge" v-bind:class="badge(props.row.type)">{{props.row.type}}</span>
                            </div>
                            <div slot="details" slot-scope="props">
                                <raw :raw="props.row.original" v-if="props.row.original"></raw>
                            </div>
                        </v-client-table>
                        <pagination :table="tables[tableData.name]" v-if="paginationReady"></pagination>
                    </b-tab>
                </b-tabs>
            </div>
        </div>
    </div>
</template>

<script>
    import Abstract from './Abstract.vue'
    import {Event} from 'vue-tables-2'

    function map(matches, type) {
        return Object.keys(matches).map(function (key) {
            return {
                name: key,
                type: type,
                original: matches[key]
            };
        });
    }

    export default {
        name: 'Conditions',
        extends: Abstract,
        data() {
            return {
                errorMessage: this.$t('error.get.conditions'),
                columns: ['name', 'type', 'details']
            }
        },
        updated() {
            this.multipleTable();
        },
        methods: {
            filter(table, source) {
                Event.$emit('vue-tables.filter::' + this.filterName('byType', table), source);
            },
            options(table) {
                return this.buildTableOptions({
                    sortable: ['name', 'type', 'details'],
                    filterByColumn: true,
                    filterable: ['name'],
                    columnsClasses: {
                        name: 'column-size-limited-500',
                        type: 'column-size-limited-80 text-center',
                        details: 'column-size-limited-60 text-center',
                    },
                    headings: {
                        name: this.$t('common.name'),
                        type: this.$t('common.type'),
                        details: this.$t('common.details')
                    },
                    customFilters: [{
                        name: this.filterName('byType', table),
                        callback: function (row, query) {
                            if (!query || query === 'all') {
                                return true;
                            }
                            return row.type === query;
                        }
                    }]
                });
            },
            internalRefresh() {
                return this.$api.conditions().then(response => {
                    this.source = response.data;
                    for (let contextName in response.data.contexts) {
                        if (response.data.contexts.hasOwnProperty(contextName)) {
                            this.tableDataList[contextName] = {
                                name: contextName,
                                parent: response.data.contexts[contextName].parentId,
                                data: []
                            };
                            this.tableDataList[contextName].data = this.tableDataList[contextName].data.concat(map(response.data.contexts[contextName].positiveMatches, 'POSITIVE'));
                            this.tableDataList[contextName].data = this.tableDataList[contextName].data.concat(map(response.data.contexts[contextName].negativeMatches, 'NEGATIVE'));
                            for (let idx in response.data.contexts[contextName].unconditionalClasses) {
                                if (response.data.contexts[contextName].unconditionalClasses.hasOwnProperty(idx)) {
                                    this.tableDataList[contextName].data.push({
                                        name: response.data.contexts[contextName].unconditionalClasses[idx],
                                        type: 'UNCONDITIONAL'
                                    });
                                }
                            }
                        }
                    }
                });
            }
        }
    }
</script>
