// front/react/src/App.js
import React, {Component} from 'react';
import {createMuiTheme, MuiThemeProvider, withStyles} from '@material-ui/core/styles';
import Button from '@material-ui/core/Button';
import PropTypes, {instanceOf} from 'prop-types';
import AppBar from "@material-ui/core/AppBar/AppBar";
import Grid from "@material-ui/core/Grid/Grid";
import Toolbar from "@material-ui/core/Toolbar/Toolbar";
import Tooltip from "@material-ui/core/Tooltip/Tooltip";
import Typography from "@material-ui/core/Typography/Typography";
import Icon from "@material-ui/core/Icon/Icon";
import Menu from "@material-ui/core/Menu/Menu";
import MenuItem from "@material-ui/core/MenuItem/MenuItem";
import PopupState, {bindMenu, bindTrigger} from 'material-ui-popup-state';
import {Cookies, CookiesProvider, withCookies} from 'react-cookie';
import axios from 'axios'
import nprogress from 'nprogress'
import {BrowserRouter, Link, NavLink, Route, Switch} from "react-router-dom";
import {addLocaleData, FormattedMessage, IntlProvider} from "react-intl";
import fr from "react-intl/locale-data/fr";
import es from "react-intl/locale-data/es";

import 'highlight.js/styles/dracula.css'

import Home from './components/Home';
import AuditEvents from './components/AuditEvents';
import NotFound from './components/NotFound';
import api from './services/api';
import i18n from './services/i18n';
import logger from './services/logger';
import Notifier from './components/Notifier';

const PATHS = ['info', 'health', 'metrics', 'env', 'mappings', 'beans', 'configprops', 'loggers',
    'threaddump', 'conditions', 'httptrace', 'scheduledtasks', 'auditevents'];
const COOKIE_PREFIX = 'REACTBOOT-';

addLocaleData(fr);
addLocaleData(es);

function initNProgres() {
    let requestsCounter = 0;

    nprogress.configure({showSpinner: false});

    axios.interceptors.request.use(function (config) {
        requestsCounter++;
        nprogress.start();
        return config
    });

    axios.interceptors.response.use(function (response) {
        if ((--requestsCounter) === 0) {
            nprogress.done()
        }
        return response
    }, function (error) {
        if ((--requestsCounter) === 0) {
            nprogress.done()
        }
        return Promise.reject(error)
    });
}

const styles = {
    grow: {
        flexGrow: 1,
    },
    menuButton: {
        textTransform: 'unset',
        fontSize: 'medium',
        padding: '0 5px',
        minWidth: '20px',
        color: 'white',
        margin: '6px 8px'
    },
    menuButtonIcon: {
        fontSize: 'medium',
        marginLeft: '5px',
        marginRight: '5px'
    },
    menuItemColor: {
        cursor: 'unset',
        '&:hover': {
            backgroundColor: 'transparent'
        }
    },
    menuIconColor: {
        cursor: 'pointer'
    },
    footer: {
        height: '48px',
        bottom: 0,
        left: 0,
        width: '100%',
        position: 'fixed'
    },
    container: {
        flex: '1 1 100%',
        margin: 'auto',
        padding: '88px 24px 50px'
    },
    navLink: {
        textDecoration: 'unset',
        color: "inherit"
    }
};

class App extends Component {
    state = {
        loading: false,
        colors: ['#F44336', '#E91E63', '#9C27B0', '#673AB7', '#3F51B5', '#2196F3', '#03A9F4', '#00BCD4', '#009688',
            '#4CAF50', '#8BC34A', '#CDDC39', '#FFEB3B', '#FFC107', '#FF9800', '#FF5722', '#795548', '#607D8B',
            '#9E9E9E', '#333333'],
        color: '#607D8B',
        dark: true,
        theme: null,
        languages: {'fr': 'Français', 'en': 'English'},
        i18n: {
            locale: 'en',
            messages: {}
        },
        i18nMessages: {},
        adminAnchorEl: null,
        languageAnchorEl: null,
        colorAnchorEl: null,
        date: new Date().getFullYear(),
        version: '1.0.0',
        env: process.env.NODE_ENV,
        demo: process.env.REACT_APP_DEMO,
        paths: [],
        ready: false
    };

    componentWillMount() {
        initNProgres();
        this.setState({loading: true});

        logger.info('Running actuator website v' + this.state.version);
        if (this.state.env === 'development') {
            logger.info('Running in development environment')
        }
        if (this.state.demo === 'demo') {
            logger.info('Running demo environment specs')
        }

        let languageFromCookies = this.props.cookies.get(COOKIE_PREFIX + 'LANGUAGE');

        this.onChangeLanguage(null, languageFromCookies || 'en');
        let themeFromCookies = this.props.cookies.get(COOKIE_PREFIX + 'THEME');
        let isDark = true;
        if (themeFromCookies) {
            isDark = themeFromCookies === 'dark';
        }
        if (!isDark) {
            this.setState({
                dark: isDark
            })
        }
        let colorFromCookies = this.props.cookies.get(COOKIE_PREFIX + 'COLOR');

        this.onChangeTheme(null, colorFromCookies || '#607D8B', isDark);
        App.applyThemeToBody(isDark);

        api.actuator().then(response => {
            let paths = [];
            for (let path of PATHS) {
                if (response.data._links) {
                    if (response.data._links[path]) {
                        paths.push(path)
                    }
                }
            }
            paths.sort();
            this.setState({paths: paths});
        }).finally(() => {
            this.setState({loading: false});
        })
    }

    static applyThemeToBody(dark) {
        if (dark) {
            document.body.style.backgroundColor = '#303030'
        } else {
            document.body.style.backgroundColor = '#fafafa'
        }
    }

    onChangeDark = () => {
        let newType = this.state.dark ? 'light' : 'dark';
        this.props.cookies.set('REACTBOOT-THEME', newType, {path: '/'});
        this.setState(() => ({
            dark: !this.state.dark,
            theme: createMuiTheme({
                palette: {
                    primary: {
                        main: this.state.color
                    },
                    type: newType
                },
                typography: {
                    useNextVariants: true,
                }
            })
        }));
        App.applyThemeToBody(!this.state.dark);
    };

    onChangeLanguage = (state, locale) => {
        if (state) {
            state.close();
        }

        if (this.state.i18nMessages[locale]) {
            this.finalizeMessages(locale, this.state.i18nMessages[locale], false);
        } else {
            i18n.load(locale).then((response) => {
                this.finalizeMessages(locale, response.data, true);
            }).catch((e) => {
                logger.error('Error while getting translation: ' + locale, e);
                throw e
            })
        }
    };

    finalizeMessages = (locale, messages, saveInState) => {
        let state = {
            i18n: {
                locale: locale,
                messages: messages
            },
            ready: true
        };
        if (saveInState) {
            state.i18nMessages = {
                ...this.state.i18nMessages,
                [locale]: messages
            }
        }
        this.setState(state);
        this.props.cookies.set('REACTBOOT-LANGUAGE', locale, {path: '/'});
    };


    onChangeTheme = (state, color, type) => {
        if (state) {
            state.close();
        }
        let isDark = this.state.dark;
        if (type != null) {
            isDark = type;
        }
        let newType = isDark ? 'dark' : 'light';
        this.setState(() => ({
            color: color,
            theme: createMuiTheme({
                palette: {
                    primary: {
                        main: color
                    },
                    type: newType
                },
                typography: {
                    useNextVariants: true,
                }
            })
        }));
        this.props.cookies.set('REACTBOOT-COLOR', color, {path: '/'});
    };

    render() {
        const {theme, dark, color, colors, adminAnchorEl, colorAnchorEl, languageAnchorEl, date, version, demo, paths, i18n, languages, ready, loading} = this.state;
        const {classes} = this.props;
        return (
            <CookiesProvider>
                <IntlProvider locale={i18n.locale} messages={i18n.messages}>
                    <BrowserRouter>
                        {ready && !loading &&
                        <MuiThemeProvider theme={theme}>
                            <Notifier/>
                            <div>
                                <AppBar position="fixed">
                                    <Toolbar>
                                        <Link to="/" className={classes.navLink}>
                                            <Typography variant="h6" color="inherit">React Boot </Typography>
                                        </Link>
                                        {paths.length > 0 &&
                                        <PopupState variant="popover" popupId="demo-popup-menu">
                                            {popupState => (
                                                <React.Fragment>
                                                    <Button aria-owns={adminAnchorEl ? 'simple-menu' : null}
                                                            aria-haspopup="true" className={classes.menuButton}
                                                            {...bindTrigger(popupState)}>
                                                        <Icon className={classes.menuButtonIcon}>settings</Icon>
                                                        <FormattedMessage id="header.admin"/>
                                                        <Icon className={classes.menuButtonIcon}>arrow_drop_down</Icon>
                                                    </Button>
                                                    <Menu {...bindMenu(popupState)}>
                                                        {paths.map((path, i) =>
                                                            <NavLink to={'/' + path} key={i} activeStyle={{
                                                                color: theme.palette.primary.main,
                                                                textDecoration: 'unset'
                                                            }} onClick={popupState.close}
                                                                     className={classes.navLink}>
                                                                <MenuItem>
                                                                    <FormattedMessage id={'header.' + path}/>
                                                                </MenuItem>
                                                            </NavLink>
                                                        )}
                                                    </Menu>
                                                </React.Fragment>
                                            )}
                                        </PopupState>
                                        }
                                        <div className={classes.grow}/>
                                        <PopupState variant="popover" popupId="demo-popup-menu">
                                            {popupState => (
                                                <React.Fragment>
                                                    <Button aria-owns={languageAnchorEl ? 'simple-menu' : null}
                                                            aria-haspopup="true" className={classes.menuButton}
                                                            {...bindTrigger(popupState)}>
                                                        <Icon className={classes.menuButtonIcon}>flag</Icon>
                                                        <FormattedMessage id="header.language"/>
                                                        <Icon className={classes.menuButtonIcon}>arrow_drop_down</Icon>
                                                    </Button>
                                                    <Menu {...bindMenu(popupState)}>
                                                        {Object.keys(languages).filter(lang => lang !== i18n.locale).map((lang, index) =>
                                                            <MenuItem key={index}
                                                                      onClick={() => this.onChangeLanguage(popupState, lang)}>
                                                                {languages[lang]}
                                                            </MenuItem>
                                                        )}
                                                    </Menu>
                                                </React.Fragment>
                                            )}
                                        </PopupState>
                                        <PopupState variant="popover" popupId="demo-popup-menu">
                                            {popupState => (
                                                <React.Fragment>
                                                    <Button aria-owns={colorAnchorEl ? 'simple-menu' : null}
                                                            aria-haspopup="true" className={classes.menuButton}
                                                            {...bindTrigger(popupState)}>
                                                        <Icon className={classes.menuButtonIcon}>format_paint</Icon>
                                                        <FormattedMessage id="header.color"/>
                                                        <Icon className={classes.menuButtonIcon}>arrow_drop_down</Icon>
                                                    </Button>
                                                    <Menu {...bindMenu(popupState)}>
                                                        {[1, 2, 3, 4].map((i) =>
                                                            <MenuItem key={i} className={classes.menuItemColor}>
                                                                {[1, 2, 3, 4, 5].map((j) =>
                                                                    <Icon key={j} className={classes.menuIconColor}
                                                                          onClick={() => this.onChangeTheme(popupState, colors[i + ((i - 1) * 4) + (j - 2)])}
                                                                          style={{color: colors[i + ((i - 1) * 4) + (j - 2)]}}
                                                                    >check_circle</Icon>
                                                                )}
                                                            </MenuItem>
                                                        )}
                                                    </Menu>
                                                </React.Fragment>
                                            )}
                                        </PopupState>
                                        <Tooltip title={dark
                                            ? <FormattedMessage id="header.theme.light"/>
                                            : <FormattedMessage id="header.theme.dark"/>
                                        }>
                                            <Button onClick={this.onChangeDark} className={classes.menuButton}>
                                                <Icon className={classes.menuButtonIcon}>invert_colors</Icon>
                                                <FormattedMessage id="header.theme"/>
                                            </Button>
                                        </Tooltip>
                                    </Toolbar>
                                </AppBar>
                            </div>
                            <div className={classes.container}>
                                <Switch>
                                    <Route path="/" exact component={Home}/>
                                    <Route path="/auditevents" component={AuditEvents}/>
                                    <Route component={NotFound}/>
                                </Switch>
                            </div>
                            <footer className={classes.footer}>
                                <AppBar position="sticky" color={"default"}>
                                    <Toolbar variant="dense">
                                        <Grid container direction="row" justify="center" alignItems="center">
                                            <Typography color="inherit" align="center">
                                                <span>Copyright © {date} | </span>
                                                <a href="https://github.com/fonimus/actuator-site-spring-boot"
                                                   style={{color: color}}>
                                                    <span>Actuator site for Spring Boot</span>
                                                </a>
                                                <span> @ </span>
                                                <a href="https://github.com/fonimus" style={{color: color}}>fonimus</a>
                                                {version &&
                                                <span> | v{version}</span>
                                                }
                                                {demo &&
                                                <span> | Demo environment</span>
                                                }
                                            </Typography>
                                        </Grid>
                                    </Toolbar>
                                </AppBar>
                            </footer>
                        </MuiThemeProvider>
                        }
                    </BrowserRouter>
                </IntlProvider>
            </CookiesProvider>
        );
    }
}

App.propTypes = {
    classes: PropTypes.object.isRequired,
    cookies: instanceOf(Cookies).isRequired
};

export default withCookies(withStyles(styles)(App));

// front/vue/src/pages/App.vue
<template>
    <div v-if="ready" v-bind:class="{ 'page-dark': dark }">

        <notifications group="general" position="top right" classes="notification-custom" :width="300" :duration="5000"
                       :speed="500"/>

        <b-modal ref="confirmModal" title="Confirm">
        </b-modal>

        <b-navbar toggleable="md" :type="dark ? 'dark': 'light'" :variant="dark ? 'dark': 'light'" sticky="true">

            <b-navbar-toggle target="nav_collapse"></b-navbar-toggle>

            <b-navbar-brand to="/">{{$t('header.title')}}</b-navbar-brand>

            <b-collapse is-nav id="nav_collapse">

                <b-navbar-nav>

                    <b-nav-item-dropdown v-if="paths.length > 0">
                        <template slot="button-content">
                            <fa icon="cog" class="space"/>
                            <span>{{$t('header.admin')}}</span>
                        </template>
                        <b-dropdown-item v-for="(path,key) of paths" :key="key" :to="'/admin/'+ path">
                            {{$t('header.'+path)}}
                        </b-dropdown-item>
                    </b-nav-item-dropdown>

                </b-navbar-nav>

                <b-navbar-nav class="ml-auto">

                    <b-nav-item-dropdown right>
                        <template slot="button-content">
                            <fa icon="flag" class="space"/>
                            <span>{{$t('header.language')}}</span>
                        </template>
                        <b-dropdown-item v-for="(display,key) of languages" :key="key"
                                         @click="setLanguage(key)" v-if="current() !== key">{{display}}
                        </b-dropdown-item>
                    </b-nav-item-dropdown>

                    <b-nav-item-dropdown right>
                        <template slot="button-content">
                            <fa icon="paint-brush" class="space"/>
                            <span>{{$t('header.theme')}}</span>
                        </template>
                        <b-dropdown-item @click="switchTheme">
                            <span>
                                <span v-if="dark">{{$t('header.theme.light')}}</span>
                                <span v-if="!dark">{{$t('header.theme.dark')}}</span>
                            </span>
                        </b-dropdown-item>
                    </b-nav-item-dropdown>

                </b-navbar-nav>

            </b-collapse>
        </b-navbar>

        <br/>

        <keep-alive>
            <div class="container-fluid" v-bind:class="{ 'container-dark': dark }">
                <router-view v-cloak :dark="dark"></router-view>
            </div>
        </keep-alive>

        <!-- Footer -->
        <footer class="footer" v-bind:class="{ 'footer-dark': dark }">
            <div class="text-center py-3">
                <span>Copyright © {{ new Date().getFullYear() }} | </span>
                <a href="https://github.com/fonimus/vue-actuator-spring-boot">
                    <span>Vue Actuatorfor Spring Boot</span>
                </a>
                <span> @ </span>
                <a href="https://github.com/fonimus">fonimus</a>
                <span v-if="version"> | v{{version}}</span>
                <span v-if="demo"> | Demo environment</span>
            </div>
        </footer>
    </div>
</template>

<script>
    import Vue from 'vue'

    const PATHS = ['info', 'health', 'metrics', 'env', 'mappings', 'beans', 'configprops', 'loggers',
        'threaddump', 'conditions', 'httptrace', 'scheduledtasks', 'auditevents'];

    export default {
        name: 'App',
        actuator: PATHS,
        components: {},
        data: function () {
            return {
                languages: {'fr': 'Français', 'en': 'English'},
                ready: false,
                loading: false,
                source: null,
                error: null,
                paths: [],
                dark: false,
                demo: false
            }
        },
        methods: {
            current() {
                return Vue.i18n.locale()
            },
            setLanguage(language) {
                this.$languages.changeLanguage(language).then(() => {
                    this.$cookies.set('VUEBOOT-LANGUAGE', language);
                });
            },
            switchTheme() {
                this.dark = !this.dark;
                this.$cookies.set('VUEBOOT-THEME', this.dark ? 'dark' : 'light');
                this.applyTheme();
            },
            applyTheme() {
                if (this.dark) {
                    document.body.classList.add('page-dark-color')
                } else {
                    document.body.classList.remove('class', 'page-dark-color')
                }
            }
        },
        mounted() {
            let languageFromCookies = this.$cookies.get('VUEBOOT-LANGUAGE');
            let language = languageFromCookies ? languageFromCookies : 'en';
            this.$languages.changeLanguage(language).finally(() => {
                this.ready = true;
            });
            let themeFromCookies = this.$cookies.get('VUEBOOT-THEME');
            if (themeFromCookies) {
                this.dark = themeFromCookies === 'dark';
                this.applyTheme();
            }
        },
        created() {
            this.env = env;
            this.demo = demo;
            if (this.env === 'development') {
                this.languages['zn'] = '[dev] no-translations';
                this.$log.info('Running in developpement environment');
            }
            if (demo === 'demo') {
                this.$log.info('Running demo environment specs');
            }
            this.version = version;
            this.loading = true;
            this.$api.actuator().then(response => {
                this.paths = [];
                for (let path of PATHS) {
                    if (response.data._links[path]) {
                        this.paths.push(path);
                    }
                }
                this.paths.sort();
            }).catch(e => {
                this.$notify({group: 'general', type: 'error', title: this.$t('error.get.actuator')});
                this.$log.error('Error while available actuator endpoints: ', e);
                this.error = e
            }).finally(() => {
                this.loading = false
            })
        }
    }
</script>

<style lang="scss">

    $primary: #6800c1;
    $my-progress-color: $primary;

    $tooltip-max-width: 500px;

    $page-dark-bg: #232323;

    @import '~bootstrap/scss/bootstrap.scss';
    @import '~bootstrap-vue/dist/bootstrap-vue.css';
    @import '~spinners/stylesheets/spinners';

    .vue-spinner-outer {
        text-align: center;
        padding-top: 150px;
        padding-bottom: 150px;
    }

    .vue-spinner {
        @include spinner(6em, 1.2s, background rgba(0, 0, 0, .2), 4px solid $primary);
    }

    [v-cloak] {
        display: none;
    }

    .page-dark-color {
        background-color: $page-dark-bg;
    }

    .link-white {
        @extend .text-white;
        text-decoration: underline;
    }

    .page-dark {
        @extend .page-dark-color;
    }

    .page-dark .dropdown-menu {
        background-color: $page-dark-bg;
        color: $white;
    }

    .page-dark .dropdown-item {
        color: unset;
    }

    .page-dark .dropdown-item:hover, .page-dark .dropdown-item:focus {
        color: $white;
        background-color: rgba($primary, .4);
    }

    .page-dark .form-control {
        background-color: $page-dark-bg;
        color: $white;
    }

    .page-dark .modal-header, .page-dark .modal-body, .page-dark .modal-content, .page-dark .modal-footer {
        background-color: $page-dark-bg;
    }

    .page-dark a.page-link {
        background-color: $dark;
    }

    .page-dark .page-item.disabled .page-link {
        background-color: $page-dark-bg;
    }

    .page-dark .page-item.active .page-link {
        border-color: $white;
    }

    .container-dark, .container-dark table {
        @extend .text-white;
    }

    .container-dark a {
        @extend .link-white;
    }

    .container-dark .card-header {
        @extend .bg-dark;
        border-bottom: 1px solid white;
    }

    .container-dark .card-body {
        @extend .bg-dark;
    }

    .footer-dark {
        @extend .text-white;
        margin-top: 10px;
        border-top: $card-border-width solid $card-border-color;
    }

    .footer-dark a {
        @extend .link-white;
    }

    form {
        margin-bottom: 0;
    }

    .filters {
        margin-bottom: 20px;
    }

    .white-space-normal {
        white-space: normal;
    }

    /* Tools  */

    .pointer {
        cursor: pointer;
    }

    .tab-link {
        @extend .pointer;
        color: $primary;
        text-decoration: underline;
    }

    .space {
        margin-right: 10px;
    }

    /* Bootstrap overrides  */

    .bg-light {
        border-bottom: $card-border-width solid $card-border-color;
    }

    .nav-tabs {
        margin-bottom: 15px;
    }

    .nav-pills {
        margin-bottom: 10px;
        padding-bottom: 5px;
        border-bottom: 1px solid $primary;
    }

    /* Notifications  */

    .notification-custom {
        padding: 10px;
        margin: 5px 5px 0 0;

        font-size: 14px;

        color: #ffffff;
        background: #44A4FC !important;
        border-left: 5px solid #187FE7 !important;

        &.warn {
            background: #ffb648 !important;
            border-left-color: #f48a06 !important;
        }

        &.error {
            background: #E54D42 !important;
            border-left-color: #B82E24 !important;
        }

        &.success {
            background: #68CD86 !important;
            border-left-color: #42A85F !important;
        }
    }

    /* Progress */

    #nprogress {
        pointer-events: none;
    }

    #nprogress .bar {
        background: $my-progress-color;

        position: fixed;
        z-index: 1031;
        top: 0;
        left: 0;

        width: 100%;
        height: 2px;
    }

    /* Fancy blur effect */
    #nprogress .peg {
        display: block;
        position: absolute;
        right: 0px;
        width: 100px;
        height: 100%;
        box-shadow: 0 0 10px $my-progress-color, 0 0 5px $my-progress-color;
        opacity: 1.0;

        -webkit-transform: rotate(3deg) translate(0px, -4px);
        -ms-transform: rotate(3deg) translate(0px, -4px);
        transform: rotate(3deg) translate(0px, -4px);
    }

    #nprogress .spinner {
        display: block;
        position: fixed;
        z-index: 1031;
        top: 15px;
        right: 15px;
    }

    #nprogress .spinner-icon {
        width: 18px;
        height: 18px;
        box-sizing: border-box;

        border: solid 2px transparent;
        border-top-color: $my-progress-color;
        border-left-color: $my-progress-color;
        border-radius: 50%;

        -webkit-animation: nprogress-spinner 400ms linear infinite;
        animation: nprogress-spinner 400ms linear infinite;
    }

    .nprogress-custom-parent {
        overflow: hidden;
        position: relative;
    }

    .nprogress-custom-parent #nprogress .spinner,
    .nprogress-custom-parent #nprogress .bar {
        position: absolute;
    }

    @-webkit-keyframes nprogress-spinner {
        0% {
            -webkit-transform: rotate(0deg);
        }
        100% {
            -webkit-transform: rotate(360deg);
        }
    }

    @keyframes nprogress-spinner {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }

    /* Tables */

    .sort::after {
        content: '\00A0\00A0\21C5';
    }

    .sort-up::after {
        content: '\00A0\00A0\2191';
    }

    .sort-down::after {
        content: '\00A0\00A0\2193';
    }

    .VueTables > .row {
        display: none;
    }

    .VuePagination {
        display: none;
    }

    .VuePagination__pagination {
        float: right;
    }

    .VueTables__child-row-toggler {
        width: 10px;
        height: 10px;
        line-height: 10px;
        display: block;
        margin: auto;
        text-align: center;
    }

    .VueTables__child-row-toggler--closed::before {
        @extend .pointer;
        content: "+";
    }

    .VueTables__child-row-toggler--open::before {
        @extend .pointer;
        content: "-";
    }

    @for $max from 1 through 50 {
        .column-size-limited-#{$max}0 {
            max-width: #{$max * 10}px;
            text-overflow: ellipsis;
            white-space: nowrap;
            overflow: hidden;
        }
    }


</style>
