// front/react/src/App.js
import React, {Component} from 'react';
import {createMuiTheme, MuiThemeProvider, withStyles} from '@material-ui/core/styles';
import Button from '@material-ui/core/Button';
import PropTypes, {instanceOf} from 'prop-types';
import AppBar from "@material-ui/core/AppBar/AppBar";
import Grid from "@material-ui/core/Grid/Grid";
import Toolbar from "@material-ui/core/Toolbar/Toolbar";
import Tooltip from "@material-ui/core/Tooltip/Tooltip";
import Typography from "@material-ui/core/Typography/Typography";
import Icon from "@material-ui/core/Icon/Icon";
import Menu from "@material-ui/core/Menu/Menu";
import MenuItem from "@material-ui/core/MenuItem/MenuItem";
import PopupState, {bindMenu, bindTrigger} from 'material-ui-popup-state';
import {Cookies, CookiesProvider, withCookies} from 'react-cookie';
import axios from 'axios'
import nprogress from 'nprogress'
import {BrowserRouter, Link, NavLink, Route, Switch} from "react-router-dom";
import {addLocaleData, FormattedMessage, IntlProvider} from "react-intl";
import fr from "react-intl/locale-data/fr";
import es from "react-intl/locale-data/es";

import 'highlight.js/styles/dracula.css'

import Home from './components/Home';
import AuditEvents from './components/AuditEvents';
import NotFound from './components/NotFound';
import api from './services/api';
import i18n from './services/i18n';
import logger from './services/logger';
import Notifier from './components/Notifier';

const PATHS = ['info', 'health', 'metrics', 'env', 'mappings', 'beans', 'configprops', 'loggers',
    'threaddump', 'conditions', 'httptrace', 'scheduledtasks', 'auditevents'];
const COOKIE_PREFIX = 'REACTBOOT-';

addLocaleData(fr);
addLocaleData(es);

function initNProgres() {
    let requestsCounter = 0;

    nprogress.configure({showSpinner: false});

    axios.interceptors.request.use(function (config) {
        requestsCounter++;
        nprogress.start();
        return config
    });

    axios.interceptors.response.use(function (response) {
        if ((--requestsCounter) === 0) {
            nprogress.done()
        }
        return response
    }, function (error) {
        if ((--requestsCounter) === 0) {
            nprogress.done()
        }
        return Promise.reject(error)
    });
}

const styles = {
    grow: {
        flexGrow: 1,
    },
    menuButton: {
        textTransform: 'unset',
        fontSize: 'medium',
        padding: '0 5px',
        minWidth: '20px',
        color: 'white',
        margin: '6px 8px'
    },
    menuButtonIcon: {
        fontSize: 'medium',
        marginLeft: '5px',
        marginRight: '5px'
    },
    menuItemColor: {
        cursor: 'unset',
        '&:hover': {
            backgroundColor: 'transparent'
        }
    },
    menuIconColor: {
        cursor: 'pointer'
    },
    footer: {
        height: '48px',
        bottom: 0,
        left: 0,
        width: '100%',
        position: 'fixed'
    },
    container: {
        flex: '1 1 100%',
        margin: 'auto',
        padding: '88px 24px 50px'
    },
    navLink: {
        textDecoration: 'unset',
        color: "inherit"
    }
};

class App extends Component {
    state = {
        loading: false,
        colors: ['#F44336', '#E91E63', '#9C27B0', '#673AB7', '#3F51B5', '#2196F3', '#03A9F4', '#00BCD4', '#009688',
            '#4CAF50', '#8BC34A', '#CDDC39', '#FFEB3B', '#FFC107', '#FF9800', '#FF5722', '#795548', '#607D8B',
            '#9E9E9E', '#333333'],
        color: '#607D8B',
        dark: true,
        theme: null,
        languages: {'fr': 'Français', 'en': 'English'},
        i18n: {
            locale: 'en',
            messages: {}
        },
        i18nMessages: {},
        adminAnchorEl: null,
        languageAnchorEl: null,
        colorAnchorEl: null,
        date: new Date().getFullYear(),
        version: '1.0.0',
        env: process.env.NODE_ENV,
        demo: process.env.REACT_APP_DEMO,
        paths: [],
        ready: false
    };

    componentWillMount() {
        initNProgres();
        this.setState({loading: true});

        logger.info('Running actuator website v' + this.state.version);
        if (this.state.env === 'development') {
            logger.info('Running in development environment')
        }
        if (this.state.demo === 'demo') {
            logger.info('Running demo environment specs')
        }

        let languageFromCookies = this.props.cookies.get(COOKIE_PREFIX + 'LANGUAGE');

        this.onChangeLanguage(null, languageFromCookies || 'en');
        let themeFromCookies = this.props.cookies.get(COOKIE_PREFIX + 'THEME');
        let isDark = true;
        if (themeFromCookies) {
            isDark = themeFromCookies === 'dark';
        }
        if (!isDark) {
            this.setState({
                dark: isDark
            })
        }
        let colorFromCookies = this.props.cookies.get(COOKIE_PREFIX + 'COLOR');

        this.onChangeTheme(null, colorFromCookies || '#607D8B', isDark);
        App.applyThemeToBody(isDark);

        api.actuator().then(response => {
            let paths = [];
            for (let path of PATHS) {
                if (response.data._links) {
                    if (response.data._links[path]) {
                        paths.push(path)
                    }
                }
            }
            paths.sort();
            this.setState({paths: paths});
        }).finally(() => {
            this.setState({loading: false});
        })
    }

    static applyThemeToBody(dark) {
        if (dark) {
            document.body.style.backgroundColor = '#303030'
        } else {
            document.body.style.backgroundColor = '#fafafa'
        }
    }

    onChangeDark = () => {
        let newType = this.state.dark ? 'light' : 'dark';
        this.props.cookies.set('REACTBOOT-THEME', newType, {path: '/'});
        this.setState(() => ({
            dark: !this.state.dark,
            theme: createMuiTheme({
                palette: {
                    primary: {
                        main: this.state.color
                    },
                    type: newType
                },
                typography: {
                    useNextVariants: true,
                }
            })
        }));
        App.applyThemeToBody(!this.state.dark);
    };

    onChangeLanguage = (state, locale) => {
        if (state) {
            state.close();
        }

        if (this.state.i18nMessages[locale]) {
            this.finalizeMessages(locale, this.state.i18nMessages[locale], false);
        } else {
            i18n.load(locale).then((response) => {
                this.finalizeMessages(locale, response.data, true);
            }).catch((e) => {
                logger.error('Error while getting translation: ' + locale, e);
                throw e
            })
        }
    };

    finalizeMessages = (locale, messages, saveInState) => {
        let state = {
            i18n: {
                locale: locale,
                messages: messages
            },
            ready: true
        };
        if (saveInState) {
            state.i18nMessages = {
                ...this.state.i18nMessages,
                [locale]: messages
            }
        }
        this.setState(state);
        this.props.cookies.set('REACTBOOT-LANGUAGE', locale, {path: '/'});
    };


    onChangeTheme = (state, color, type) => {
        if (state) {
            state.close();
        }
        let isDark = this.state.dark;
        if (type != null) {
            isDark = type;
        }
        let newType = isDark ? 'dark' : 'light';
        this.setState(() => ({
            color: color,
            theme: createMuiTheme({
                palette: {
                    primary: {
                        main: color
                    },
                    type: newType
                },
                typography: {
                    useNextVariants: true,
                }
            })
        }));
        this.props.cookies.set('REACTBOOT-COLOR', color, {path: '/'});
    };

    render() {
        const {theme, dark, color, colors, adminAnchorEl, colorAnchorEl, languageAnchorEl, date, version, demo, paths, i18n, languages, ready, loading} = this.state;
        const {classes} = this.props;
        return (
            <CookiesProvider>
                <IntlProvider locale={i18n.locale} messages={i18n.messages}>
                    <BrowserRouter>
                        {ready && !loading &&
                        <MuiThemeProvider theme={theme}>
                            <Notifier/>
                            <div>
                                <AppBar position="fixed">
                                    <Toolbar>
                                        <Link to="/" className={classes.navLink}>
                                            <Typography variant="h6" color="inherit">React Boot </Typography>
                                        </Link>
                                        {paths.length > 0 &&
                                        <PopupState variant="popover" popupId="demo-popup-menu">
                                            {popupState => (
                                                <React.Fragment>
                                                    <Button aria-owns={adminAnchorEl ? 'simple-menu' : null}
                                                            aria-haspopup="true" className={classes.menuButton}
                                                            {...bindTrigger(popupState)}>
                                                        <Icon className={classes.menuButtonIcon}>settings</Icon>
                                                        <FormattedMessage id="header.admin"/>
                                                        <Icon className={classes.menuButtonIcon}>arrow_drop_down</Icon>
                                                    </Button>
                                                    <Menu {...bindMenu(popupState)}>
                                                        {paths.map((path, i) =>
                                                            <NavLink to={'/' + path} key={i} activeStyle={{
                                                                color: theme.palette.primary.main,
                                                                textDecoration: 'unset'
                                                            }} onClick={popupState.close}
                                                                     className={classes.navLink}>
                                                                <MenuItem>
                                                                    <FormattedMessage id={'header.' + path}/>
                                                                </MenuItem>
                                                            </NavLink>
                                                        )}
                                                    </Menu>
                                                </React.Fragment>
                                            )}
                                        </PopupState>
                                        }
                                        <div className={classes.grow}/>
                                        <PopupState variant="popover" popupId="demo-popup-menu">
                                            {popupState => (
                                                <React.Fragment>
                                                    <Button aria-owns={languageAnchorEl ? 'simple-menu' : null}
                                                            aria-haspopup="true" className={classes.menuButton}
                                                            {...bindTrigger(popupState)}>
                                                        <Icon className={classes.menuButtonIcon}>flag</Icon>
                                                        <FormattedMessage id="header.language"/>
                                                        <Icon className={classes.menuButtonIcon}>arrow_drop_down</Icon>
                                                    </Button>
                                                    <Menu {...bindMenu(popupState)}>
                                                        {Object.keys(languages).filter(lang => lang !== i18n.locale).map((lang, index) =>
                                                            <MenuItem key={index}
                                                                      onClick={() => this.onChangeLanguage(popupState, lang)}>
                                                                {languages[lang]}
                                                            </MenuItem>
                                                        )}
                                                    </Menu>
                                                </React.Fragment>
                                            )}
                                        </PopupState>
                                        <PopupState variant="popover" popupId="demo-popup-menu">
                                            {popupState => (
                                                <React.Fragment>
                                                    <Button aria-owns={colorAnchorEl ? 'simple-menu' : null}
                                                            aria-haspopup="true" className={classes.menuButton}
                                                            {...bindTrigger(popupState)}>
                                                        <Icon className={classes.menuButtonIcon}>format_paint</Icon>
                                                        <FormattedMessage id="header.color"/>
                                                        <Icon className={classes.menuButtonIcon}>arrow_drop_down</Icon>
                                                    </Button>
                                                    <Menu {...bindMenu(popupState)}>
                                                        {[1, 2, 3, 4].map((i) =>
                                                            <MenuItem key={i} className={classes.menuItemColor}>
                                                                {[1, 2, 3, 4, 5].map((j) =>
                                                                    <Icon key={j} className={classes.menuIconColor}
                                                                          onClick={() => this.onChangeTheme(popupState, colors[i + ((i - 1) * 4) + (j - 2)])}
                                                                          style={{color: colors[i + ((i - 1) * 4) + (j - 2)]}}
                                                                    >check_circle</Icon>
                                                                )}
                                                            </MenuItem>
                                                        )}
                                                    </Menu>
                                                </React.Fragment>
                                            )}
                                        </PopupState>
                                        <Tooltip title={dark
                                            ? <FormattedMessage id="header.theme.light"/>
                                            : <FormattedMessage id="header.theme.dark"/>
                                        }>
                                            <Button onClick={this.onChangeDark} className={classes.menuButton}>
                                                <Icon className={classes.menuButtonIcon}>invert_colors</Icon>
                                                <FormattedMessage id="header.theme"/>
                                            </Button>
                                        </Tooltip>
                                    </Toolbar>
                                </AppBar>
                            </div>
                            <div className={classes.container}>
                                <Switch>
                                    <Route path="/" exact component={Home}/>
                                    <Route path="/auditevents" component={AuditEvents}/>
                                    <Route component={NotFound}/>
                                </Switch>
                            </div>
                            <footer className={classes.footer}>
                                <AppBar position="sticky" color={"default"}>
                                    <Toolbar variant="dense">
                                        <Grid container direction="row" justify="center" alignItems="center">
                                            <Typography color="inherit" align="center">
                                                <span>Copyright © {date} | </span>
                                                <a href="https://github.com/fonimus/actuator-site-spring-boot"
                                                   style={{color: color}}>
                                                    <span>Actuator site for Spring Boot</span>
                                                </a>
                                                <span> @ </span>
                                                <a href="https://github.com/fonimus" style={{color: color}}>fonimus</a>
                                                {version &&
                                                <span> | v{version}</span>
                                                }
                                                {demo &&
                                                <span> | Demo environment</span>
                                                }
                                            </Typography>
                                        </Grid>
                                    </Toolbar>
                                </AppBar>
                            </footer>
                        </MuiThemeProvider>
                        }
                    </BrowserRouter>
                </IntlProvider>
            </CookiesProvider>
        );
    }
}

App.propTypes = {
    classes: PropTypes.object.isRequired,
    cookies: instanceOf(Cookies).isRequired
};

export default withCookies(withStyles(styles)(App));

// front/vue/src/App.vue
<template>
    <v-app :dark="dark" v-if="ready">
        <!-- TODO is navigation required ?-->
        <!--<v-navigation-drawer persistent :mini-variant="miniVariant" :clipped="clipped" v-model="drawer"-->
        <!--enable-resize-watcher fixed app>-->
        <!--<v-list>-->
        <!--<v-list-tile value="true" v-for="(item, i) in items" :key="i">-->
        <!--<v-list-tile-action>-->
        <!--<v-icon v-html="item.icon"></v-icon>-->
        <!--</v-list-tile-action>-->
        <!--<v-list-tile-content>-->
        <!--<v-list-tile-title v-text="item.title"></v-list-tile-title>-->
        <!--</v-list-tile-content>-->
        <!--</v-list-tile>-->
        <!--</v-list>-->
        <!--</v-navigation-drawer>-->
        <v-toolbar app :clipped-left="clipped" color="primary">
            <!--<v-toolbar-side-icon @click.stop="drawer = !drawer"></v-toolbar-side-icon>-->
            <!--<v-btn icon @click.stop="miniVariant = !miniVariant">-->
            <!--<v-icon v-html="miniVariant ? 'chevron_right' : 'chevron_left'"></v-icon>-->
            <!--</v-btn>-->
            <!-- TODO find logo -->
            <v-toolbar-title v-text="title" @click="home" class="pointer white--text"></v-toolbar-title>

            <v-menu offset-y v-if="paths.length > 0">
                <v-btn slot="activator" color="primary" depressed class="v-btn--header">
                    <v-icon left>settings</v-icon>
                    <span v-t="'header.admin'" class="hidden-sm-and-down"></span>
                    <v-icon left>arrow_drop_down</v-icon>
                </v-btn>
                <v-list color="primary">
                    <v-list-tile v-for="(path, index) in paths" :key="index" :to="'/'+ path">
                        <v-list-tile-title>{{$t('header.' + path)}}</v-list-tile-title>
                    </v-list-tile>
                </v-list>
            </v-menu>

            <v-spacer></v-spacer>

            <v-menu offset-y>
                <v-btn slot="activator" color="primary" depressed class="v-btn--header">
                    <v-icon left>flag</v-icon>
                    <span v-t="'header.language'" class="hidden-sm-and-down"></span>
                    <v-icon left>arrow_drop_down</v-icon>
                </v-btn>
                <v-list>
                    <v-list-tile v-for="(display,key) of languages" :key="key" @click="setLanguage(key)"
                                 v-if="current() !== key">
                        <v-list-tile-title>{{display}}</v-list-tile-title>
                    </v-list-tile>
                </v-list>
            </v-menu>

            <v-menu offset-y>
                <v-btn slot="activator" color="primary" depressed class="v-btn--header">
                    <v-icon left>format_paint</v-icon>
                    <span v-t="'header.color'" class="hidden-sm-and-down"></span>
                    <v-icon left>arrow_drop_down</v-icon>
                </v-btn>
                <v-list>
                    <v-list-tile v-for="i in 4" :key="i">
                        <v-list-tile-title @click="switchColor(colors[i+((i-1)*4)+(j-2)])" v-for="j in 5" :key="j">
                            <v-icon dark v-bind:style="{color: colors[i+((i-1)*4)+(j-2)]}" class="space pointer">
                                check_circle
                            </v-icon>
                        </v-list-tile-title>
                    </v-list-tile>
                </v-list>
            </v-menu>

            <v-tooltip bottom>
                <v-btn slot="activator" color="primary" depressed class="v-btn--header" @click="switchTheme">
                    <v-icon left>invert_colors</v-icon>
                    <span v-t="'header.theme'" class="hidden-sm-and-down"></span>
                </v-btn>
                <span v-if="dark">{{$t('header.theme.light')}}</span>
                <span v-if="!dark">{{$t('header.theme.dark')}}</span>
            </v-tooltip>
        </v-toolbar>
        <v-content>
            <v-container fluid>
                <router-view/>
            </v-container>
        </v-content>
        <v-footer height="50">
            <v-flex text-xs-center>
                <span>Copyright © {{ new Date().getFullYear() }} | </span>
                <a href="https://github.com/fonimus/actuator-site-spring-boot">
                    <span>Actuator site for Spring Boot</span>
                </a>
                <span> @ </span>
                <a href="https://github.com/fonimus">fonimus</a>
                <span v-if="version"> | v{{version}}</span>
                <span v-if="demo"> | Demo environment</span>
            </v-flex>
        </v-footer>

        <v-snackbar v-model="snackbar.display" :color="snackbar.color" :timeout="snackbar.timeout">
            {{snackbar.text}}
            <v-btn dark flat icon @click="snackbar.display = false">
                <v-icon>close</v-icon>
            </v-btn>
        </v-snackbar>
    </v-app>
</template>

<script>
    import Vue from 'vue';

    const PATHS = ['info', 'health', 'metrics', 'env', 'mappings', 'beans', 'configprops', 'loggers',
        'threaddump', 'conditions', 'httptrace', 'scheduledtasks', 'auditevents'];

    export default {
        data() {
            return {
                dark: true,
                colors: ['#F44336', '#E91E63', '#9C27B0', '#673AB7', '#3F51B5', '#2196F3', '#03A9F4',
                    '#00BCD4', '#009688', '#4CAF50', '#8BC34A', '#CDDC39', '#FFEB3B', '#FFC107', '#FF9800', '#FF5722',
                    '#795548', '#607D8B', '#9E9E9E', '#333333'],
                clipped: true,
                drawer: false,
                fixed: true,
                miniVariant: false,
                right: true,
                rightDrawer: false,
                title: 'Vue Boot',

                snackbar: {
                    display: false,
                    color: 'success',
                    timeout: 3000,
                    text: 'Test',
                },

                languages: {fr: 'Français', en: 'English'},
                ready: false,
                loading: false,
                source: null,
                error: null,
                paths: [],
                demo: false,
            };
        },
        methods: {
            home() {
                this.$router.push('/');
            },
            current() {
                return Vue.i18n.locale();
            },
            setLanguage(language) {
                this.$languages.changeLanguage(language).then(() => {
                    this.$cookies.set('VUEBOOT-LANGUAGE', language);
                    this.$vuetify.lang.current = language;
                });
            },
            displaySnackbar(text, color, timeout = 3000) {
                this.snackbar.text = text;
                this.snackbar.color = color;
                this.snackbar.timeout = timeout;
                this.snackbar.display = true;
            },
            switchTheme() {
                this.dark = !this.dark;
                this.$cookies.set('VUEBOOT-THEME', this.dark ? 'dark' : 'light');
                this.applyThemeToBody();
            },
            switchColor(color) {
                this.$vuetify.theme.primary = color;
                this.$cookies.set('VUEBOOT-COLOR', color);
            },
            applyThemeToBody() {
                if (this.dark) {
                    document.body.style.backgroundColor = '#303030';
                } else {
                    document.body.style.backgroundColor = '#fafafa';
                }
            },
        },
        mounted() {
            const languageFromCookies = this.$cookies.get('VUEBOOT-LANGUAGE');
            const language = languageFromCookies || 'en';
            const themeFromCookies = this.$cookies.get('VUEBOOT-THEME');
            if (themeFromCookies) {
                this.dark = themeFromCookies === 'dark';
            }
            this.applyThemeToBody();
            const colorFromCookies = this.$cookies.get('VUEBOOT-COLOR');
            this.$vuetify.theme.primary = colorFromCookies || '#607D8B';
            this.$languages.changeLanguage(language).finally(() => {
                this.$vuetify.lang.current = language;
                this.ready = true;
            });
        },
        created() {
            this.env = process.env.NODE_ENV;
            this.demo = process.env.VUE_APP_DEMO;
            this.version = '1.0.0';
            this.$log.info('Running actuator website v' + this.version);
            if (this.env === 'development') {
                this.$log.info('Running in development environment');
            }
            if (this.demo === 'demo') {
                this.$log.info('Running demo environment specs');
            }

            Vue.prototype.$snack = {
                info: function (message, type, timeout) {
                    this.displaySnackbar(message, type, timeout);
                }.bind(this),
                success: function (message, timeout) {
                    this.displaySnackbar(message, 'success', timeout);
                }.bind(this),
                error: function (message, timeout) {
                    this.displaySnackbar(message, 'error', timeout);
                }.bind(this),
            };

            this.loading = true;
            this.$api.actuator().then((response) => {
                this.paths = [];
                for (const path of PATHS) {
                    if (response.data._links[path]) {
                        this.paths.push(path);
                    }
                }
                this.paths.sort();
            }).finally(() => {
                this.loading = false;
            });
        },
        name: 'App',
        actuator: PATHS
    };
</script>

<style lang="scss">
    .space {
        margin-right: 5px;
    }

    .pointer {
        cursor: pointer;
    }

    .filters {
        margin-left: 25px;
    }

    .v-btn--xs {
        font-size: smaller;
        min-width: 30px;
    }

    .v-btn--no-transform {
        text-transform: unset;
    }

    .v-btn--no-transform .v-icon {
        font-size: medium;
        margin-left: 5px;
    }

    .v-btn--header {
        text-transform: unset;
        font-size: larger;
        padding: 0 5px;
        min-width: 20px;
    }

    .v-btn--header .v-icon {
        font-size: medium;
        margin-left: 5px;
        margin-right: 5px;
    }

    .v-alert {
        margin-bottom: 20px;
    }

    /* Progress */

    #nprogress {
        pointer-events: none;
    }

    #nprogress .bar {
        background: white;

        position: fixed;
        z-index: 1031;
        top: 0;
        left: 0;

        width: 100%;
        height: 2px;
    }

    /* Fancy blur effect */
    #nprogress .peg {
        display: block;
        position: absolute;
        right: 0;
        width: 100px;
        height: 100%;
        box-shadow: 0 0 10px white, 0 0 5px white;
        opacity: 1.0;

        -webkit-transform: rotate(3deg) translate(0px, -4px);
        -ms-transform: rotate(3deg) translate(0px, -4px);
        transform: rotate(3deg) translate(0px, -4px);
    }

    #nprogress .spinner {
        display: block;
        position: fixed;
        z-index: 1031;
        top: 15px;
        right: 15px;
    }

    #nprogress .spinner-icon {
        width: 18px;
        height: 18px;
        box-sizing: border-box;

        border: solid 2px transparent;
        border-top-color: white;
        border-left-color: white;
        border-radius: 50%;

        -webkit-animation: nprogress-spinner 400ms linear infinite;
        animation: nprogress-spinner 400ms linear infinite;
    }

    .nprogress-custom-parent {
        overflow: hidden;
        position: relative;
    }

    .nprogress-custom-parent #nprogress .spinner,
    .nprogress-custom-parent #nprogress .bar {
        position: absolute;
    }

    @-webkit-keyframes nprogress-spinner {
        0% {
            -webkit-transform: rotate(0deg);
        }
        100% {
            -webkit-transform: rotate(360deg);
        }
    }

    @keyframes nprogress-spinner {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }
</style>
