// front/vue/src/pages/actuator/Beans.vue
<template>
    <div class="card card-page">
        <div class="card-header d-flex">
            <div><span v-t="'beans.title'"></span></div>
            <div class="ml-auto">
                <raw :raw="source"></raw>
                <fa class="pointer" icon="sync" @click="!loading && refresh()" :spin="loading" v-b-tooltip.hover
                    :title="$t('refresh.data')"/>
            </div>
        </div>
        <div class="card-body">
            <spinner :show="loading"></spinner>
            <div v-if="!loading">
                <b-tabs pills v-model="tabIndex">
                    <b-tab :title="tableData.name" :key="tableData.name" v-for="tableData of tableDataList">
                        <p v-if="tableData.parent" class="alert alert-info">
                            <span v-t="'common.parent-context'"></span>
                            <span class="tab-link" @click="tab(tableData.parent)">{{tableData.parent}}</span>
                        </p>
                        <p class="alert alert-primary">
                            <span v-t="'filter.scopes'"></span>
                            <span class="space badge pointer" @click="filter('all', tableData.name)"
                                  v-bind:class="badge('all', scopeFilter === 'all')"><span v-t="'common.all'"></span>
                            </span>
                            <span class="space badge pointer" @click="filter(scope, tableData.name)"
                                  v-bind:class="badge(scope, scopeFilter === scope)" v-for="scope in scopes"
                                  :key="scope">{{scope}}</span>
                        </p>
                        <v-client-table :ref="tableData.name" :data="tableData.data" :columns="columns"
                                        :options="options(tableData.name)">
                            <div slot="name" slot-scope="props">
                                <span v-b-tooltip.hover :title="props.row.name">{{props.row.name}}</span>
                            </div>
                            <div slot="type" slot-scope="props">
                                <span v-b-tooltip.hover :title="props.row.type">{{props.row.type}}</span>
                            </div>
                            <div slot="scope" slot-scope="props">
                                <span class="badge" v-bind:class="badge(props.row.scope)">{{props.row.scope}}</span>
                            </div>
                            <div slot="dependencies" slot-scope="props" class="white-space-normal">
                                <span class="badge space" v-bind:class="badge(scope, 'beans')"
                                      v-for="dependency in props.row.dependencies">{{dependency}}</span>
                            </div>
                            <div slot="details" slot-scope="props">
                                <raw :raw="props.row"></raw>
                            </div>
                        </v-client-table>
                        <pagination :table="tables[tableData.name]" v-if="paginationReady"></pagination>
                    </b-tab>
                </b-tabs>
            </div>
        </div>
    </div>
</template>

<script>
    import Abstract from './Abstract.vue'
    import {Event} from 'vue-tables-2'

    export default {
        name: 'Beans',
        extends: Abstract,
        data() {
            return {
                errorMessage: this.$t('error.get.beans'),
                scopes: [],
                scopeFilter: null,
                columns: ['name', 'scope', 'type', 'dependencies', 'details']
            }
        },
        updated() {
            this.multipleTable();
        },
        methods: {
            filter(scope, table) {
                this.scopeFilter = scope;
                Event.$emit('vue-tables.filter::' + this.filterName('byScope', table), scope);
            },
            options(table) {
                return this.buildTableOptions({
                    sortable: ['name', 'scope', 'type'],
                    filterByColumn: true,
                    filterable: ['name', 'type'],
                    columnsClasses: {
                        name: 'column-size-limited-300',
                        type: 'column-size-limited-300',
                        dependencies: 'column-size-limited-300',
                        scope: 'column-size-limited-80 text-center',
                        details: 'column-size-limited-60 text-center',
                    },
                    headings: {
                        name: this.$t('beans.name'),
                        scope: this.$t('beans.scope'),
                        type: this.$t('common.type'),
                        dependencies: this.$t('beans.dependencies'),
                        details: this.$t('common.details')
                    },
                    customFilters: [{
                        name: this.filterName('byScope', table),
                        callback: function (row, query) {
                            if (!query || query === 'all') {
                                return true;
                            }
                            return row.scope === query;
                        }
                    }]
                });
            },
            internalRefresh() {
                return this.$api.beans().then(response => {
                    this.source = response.data;
                    for (let contextName in response.data.contexts) {
                        if (response.data.contexts.hasOwnProperty(contextName)) {
                            this.tableDataList[contextName] = {
                                name: contextName,
                                parent: response.data.contexts[contextName].parentId,
                                data: []
                            };
                            for (let beanName in response.data.contexts[contextName].beans) {
                                if (response.data.contexts[contextName].beans.hasOwnProperty(beanName)) {
                                    const bean = {
                                        name: beanName
                                    };
                                    Object.assign(bean, response.data.contexts[contextName].beans[beanName]);
                                    this.putIfAbsent(this.scopes, bean.scope);
                                    this.tableDataList[contextName].data.push(bean);
                                }
                            }
                        }
                    }
                });
            }
        }
    }
</script>

// front/react/src/pages/Beans.js
import React, {Component} from 'react';
import Card from '@material-ui/core/Card';
import Icon from '@material-ui/core/Icon';
import PropTypes from "prop-types";
import {withStyles} from "@material-ui/core";
import {FormattedMessage, injectIntl, intlShape} from "react-intl";
import TableCell from '@material-ui/core/TableCell';
import TableRow from '@material-ui/core/TableRow';
import Input from '@material-ui/core/Input/Input';
import InputAdornment from '@material-ui/core/InputAdornment';

import api from '../services/api';
import logger from '../services/logger';
import utils from '../services/utils';
import Raw from '../components/Raw';
import ColoredButton from "../components/ColoredButton";
import ButtonFilter from "../components/ButtonFilter";
import {openSnackbar} from "../components/Notifier";
import Typography from "@material-ui/core/Typography/Typography";
import CardHeader from "../components/CardHeader";
import CardTable from "../components/CardTable";
import CardBody from "../components/CardBody";
import Grid from "@material-ui/core/Grid/Grid";
import Tabs from "@material-ui/core/Tabs/Tabs";
import Tab from "@material-ui/core/Tab/Tab";

class Beans extends Component {

    state = {
        loading: true,
        columns: [
            {id: 'name', sortable: true, i18n: 'beans.name'},
            {id: 'scope', sortable: true, i18n: 'beans.scope'},
            {id: 'type', sortable: true, i18n: 'common.type'},
            {id: 'details', sortable: false, i18n: 'common.details'},
        ],
        scopes: [],
        scopeFilters: [],
        search: '',
        tableDataList: {},
        tab: 0
    };

    componentDidMount() {
        this.refresh();
    };

    refresh() {
        this.setState({loading: true});
        api.beans().then(response => {
            let tableDataList = [];
            let scopes = [];
            for (const contextName in response.data.contexts) {
                if (response.data.contexts.hasOwnProperty(contextName)) {
                    tableDataList[contextName] = {
                        name: contextName,
                        parent: response.data.contexts[contextName].parentId,
                        data: []
                    };
                    for (const beanName in response.data.contexts[contextName].beans) {
                        if (response.data.contexts[contextName].beans.hasOwnProperty(beanName)) {
                            const bean = {
                                name: beanName
                            };
                            Object.assign(bean, response.data.contexts[contextName].beans[beanName]);
                            utils.putIfAbsent(scopes, bean.scope);
                            tableDataList[contextName].data.push(bean);
                        }
                    }
                }
            }
            this.setState({source: response.data, scopes, tableDataList});
        }).catch((e) => {
            logger.error("Error while loading beans", e);
            openSnackbar(<FormattedMessage id="error.get.beans"/>, 'error');
        }).finally(() => {
            this.setState({loading: false});
        })
    };

    filter = (list) => {
        return list.filter((value) => {
            return utils.search(this.state.search, value, ['name']) &&
                utils.inFilter(this.state.scopeFilters, value.scope);
        })
    };

    searchPlaceHolder() {
        return this.props.intl.formatMessage({id: 'common.filter'});
    };

    handleFilter = (value, onSelect) => {
        this.setState({scopeFilters: utils.buildFilter(this.state.scopeFilters, value, onSelect)});
    };

    handleChange = (event) => {
        this.setState({search: event.target.value,});
    };

    handleTabChange = (event, value) => {
        this.setState({tab: value});
    };


    render() {
        const {source, loading, columns, scopes, search, tableDataList, tab} = this.state;

        return (
            <div>
                <Card>
                    <CardHeader source={source} url="/beans" refresh={() => this.refresh()}
                                title={<FormattedMessage id={"beans.title"}/>}/>
                    <CardBody loading={loading}>
                        {tableDataList && tableDataList[Object.keys(tableDataList)[tab]] &&
                        <div>
                            <Tabs value={tab} onChange={this.handleTabChange} indicatorColor="primary"
                                  textColor="primary">

                                {Object.keys(tableDataList).map((name) => {
                                    return (
                                        <Tab key={name}
                                             label={<span><FormattedMessage id="common.context"/> : {name}</span>}/>
                                    );
                                })}
                            </Tabs>
                            <div className={"filters"} style={{marginTop: '10px'}}>
                                <Typography component={"span"}>
                                    <Grid container direction="row" justify="space-between" alignItems="center">
                                        <Grid item>
                                            <FormattedMessage id="filter.types"/>
                                            {scopes.map((scope, idx) => {
                                                return (
                                                    <ButtonFilter
                                                        key={idx} text={scope} color={utils.color(scope)}
                                                        onSelect={() => this.handleFilter(scope, true)}
                                                        onDelete={() => this.handleFilter(scope, false)}
                                                    />
                                                );
                                            })}
                                        </Grid>
                                        <Grid item xs={12} sm>
                                            <Input id="search" type={"text"} className={"full-width"}
                                                   value={search} placeholder={this.searchPlaceHolder()}
                                                   onChange={this.handleChange}
                                                   endAdornment={
                                                       <InputAdornment position="end">
                                                           <Icon>search</Icon>
                                                       </InputAdornment>
                                                   }
                                            />
                                        </Grid>
                                    </Grid>
                                </Typography>
                            </div>
                            <CardTable
                                data={tableDataList[Object.keys(tableDataList)[tab]].data} columns={columns}
                                customFilter={this.filter}
                                initialOrder={"asc"} initialOrderBy={"name"}
                                row={(row, idx) => {
                                    return (
                                        <TableRow key={idx}>
                                            <TableCell className={"column-max-name"}>{row.name}</TableCell>
                                            <TableCell>
                                                <ColoredButton size={"s"} color={utils.color(row.scope)}
                                                               text={row.scope} noTransform={true}>
                                                </ColoredButton>
                                            </TableCell>
                                            <TableCell className={"column-max-name"}>{row.type}</TableCell>
                                            <TableCell><Raw raw={row}/></TableCell>
                                        </TableRow>
                                    )
                                }}/>
                        </div>
                        }
                    </CardBody>
                </Card>
            </div>
        );
    }
}

Beans.propTypes = {
    classes: PropTypes.object.isRequired,
    intl: intlShape.isRequired
};

export default injectIntl(withStyles({...utils.defaultCardContentStyle})(Beans));
