// front/vue/src/views/HttpTrace.vue
<template>
    <actuator-card :source="source" :refresh="refresh" url="/auditevents">
        <template slot="title">
            <span v-t="'trace.title'"></span>
        </template>
        <template slot="content">
            <div class="filters">
                <div>
                    <span v-t="'filter.methods'"></span>
                    <button-filter v-for="method in methods" :key="method" :name="method"
                                   :on-select="activate.bind(this, methodFilters, method)"
                                   :on-remove="deactivate.bind(this, methodFilters, method)"
                                   :color="color(method)">

                    </button-filter>
                </div>
                <div>
                    <span v-t="'filter.statuses'"></span>
                    <button-filter v-for="status in statuses" :key="status" :name="status"
                                   :on-select="activate.bind(this, statusFilters, status)"
                                   :on-remove="deactivate.bind(this, statusFilters, status)"
                                   :color="color(status)">

                    </button-filter>
                </div>

                <v-text-field v-model="search" append-icon="search" :label="$t('common.filter')"
                              single-line hide-details>

                </v-text-field>
            </div>

            <v-data-table :headers="headers" :items="rows" :search="search" :loading="loading"
                          :pagination.sync="pagination" :rows-per-page-items="itemsPerPage">
                <template slot="items" slot-scope="props">
                    <td>{{ props.item.timestamp | date}}</td>
                    <td>
                        <v-btn small round :color="color(props.item.response.status)">{{ props.item.response.status }}
                        </v-btn>
                    </td>
                    <td>{{ props.item.timeTaken }}</td>
                    <td>
                        <v-btn small round :color="color(props.item.request.method)">{{ props.item.request.method}}
                        </v-btn>
                    </td>
                    <td>{{ props.item.request.uri }}</td>
                    <td>
                        <raw :raw="props.item"></raw>
                    </td>
                </template>
            </v-data-table>
        </template>
    </actuator-card>
</template>

<script>
    import Abstract from './Abstract.vue';

    function status(allowed, aStatus) {
        if (!allowed || allowed.length === 0) {
            return true;
        }
        if (aStatus >= 200 && aStatus < 300) {
            return allowed.indexOf('2XX') !== -1;
        } else if (aStatus >= 300 && aStatus < 400) {
            return allowed.indexOf('3XX') !== -1;
        } else if (aStatus >= 400 && aStatus < 500) {
            return allowed.indexOf('4XX') !== -1;
        } else if (aStatus >= 500 && aStatus < 600) {
            return allowed.indexOf('5XX') !== -1;
        }
        return false;
    }

    function method(allowed, aMethod) {
        return !allowed || allowed.length === 0 || allowed.indexOf(aMethod) > -1;
    }

    export default {
        extends: Abstract,
        data() {
            return {
                errorMessage: this.$t('error.get.trace'),
                methodFilters: [],
                statuses: ['2XX', '3XX', '4XX', '5XX'],
                statusFilters: [],
                pagination: {sortBy: 'timestamp', descending: true, rowsPerPage: 10}
            };
        },
        methods: {
            internalRefresh() {
                return this.$api.httptrace().then((response) => {
                    this.source = response.data;
                    this.tableData = response.data.traces;
                });
            }
        },
        computed: {
            rows() {
                if (this.methodFilters.length === 0 && this.statusFilters.length === 0) {
                    return this.tableData;
                }
                this.pagination.page = 1;
                return this.tableData.filter((value) =>
                    method(this.methodFilters, value.request.method) &&
                    status(this.statusFilters, value.response.status));
            },
            headers() {
                return [
                    {text: this.$t('common.timestamp'), value: 'timestamp'},
                    {text: this.$t('common.status'), value: 'response.status'},
                    {text: this.$t('trace.time-taken'), value: 'timeTaken'},
                    {text: this.$t('common.method'), value: 'request.method'},
                    {text: this.$t('trace.uri'), value: 'request.uri'},
                    {text: this.$t('common.details'), value: 'none'}
                ];
            }
        }
    };
</script>

// front/react/src/pages/HttpTrace.js
import React, {Component} from 'react';
import Card from '@material-ui/core/Card';
import Icon from '@material-ui/core/Icon';
import PropTypes from "prop-types";
import {withStyles} from "@material-ui/core";
import {FormattedMessage, injectIntl, intlShape} from "react-intl";
import TableCell from '@material-ui/core/TableCell';
import TableRow from '@material-ui/core/TableRow';
import Input from '@material-ui/core/Input/Input';
import InputAdornment from '@material-ui/core/InputAdornment';

import api from '../services/api';
import logger from '../services/logger';
import utils from '../services/utils';
import Raw from '../components/Raw';
import ColoredButton from "../components/ColoredButton";
import ButtonFilter from "../components/ButtonFilter";
import {openSnackbar} from "../components/Notifier";
import Typography from "@material-ui/core/Typography/Typography";
import CardHeader from "../components/CardHeader";
import CardTable from "../components/CardTable";
import CardBody from "../components/CardBody";

function status(allowed, aStatus) {
    if (!allowed || allowed.length === 0) {
        return true;
    }
    if (aStatus >= 200 && aStatus < 300) {
        return allowed.indexOf('2XX') !== -1;
    } else if (aStatus >= 300 && aStatus < 400) {
        return allowed.indexOf('3XX') !== -1;
    } else if (aStatus >= 400 && aStatus < 500) {
        return allowed.indexOf('4XX') !== -1;
    } else if (aStatus >= 500 && aStatus < 600) {
        return allowed.indexOf('5XX') !== -1;
    }
    return false;
}

function method(allowed, aMethod) {
    return !allowed || allowed.length === 0 || allowed.indexOf(aMethod) > -1;
}

class HttpTrace extends Component {

    state = {
        source: null,
        loading: true,
        columns: [
            {id: 'timestamp', sortable: true, i18n: 'common.timestamp'},
            {id: 'response.status', sortable: true, i18n: 'common.status'},
            {id: 'timeTaken', sortable: true, i18n: 'trace.time-taken'},
            {id: 'request.method', sortable: true, i18n: 'common.method'},
            {id: 'request.uri', sortable: true, i18n: 'trace.uri'},
            {id: 'details', sortable: false, i18n: 'common.details'},
        ],
        methodFilters: [],
        statusFilters: [],
        search: ''
    };

    componentDidMount() {
        this.refresh();
    };

    refresh() {
        this.setState({loading: true});
        api.httptrace().then(response => {
            this.setState({
                source: response.data
            })
        }).catch((e) => {
            logger.error("Error while loading traces", e);
            openSnackbar(<FormattedMessage id="error.get.trace"/>, 'error');
        }).finally(() => {
            this.setState({loading: false});
        })
    };

    searchPlaceHolder() {
        return this.props.intl.formatMessage({id: 'common.filter'});
    };

    handleFilter = (type, value, onSelect) => {
        switch (type) {
            case 'method':
                this.setState({methodFilters: utils.buildFilter(this.state.methodFilters, value, onSelect)});
                break;
            case 'status':
                this.setState({statusFilters: utils.buildFilter(this.state.statusFilters, value, onSelect)});
                break;
            default:
                return;
        }
    };

    filter = (list) => {
        return list.filter((value) => {
            return utils.search(this.state.search, value, ['timeTaken', 'request.uri', 'request.method', 'response.status']) &&
                method(this.state.methodFilters, value.request.method) &&
                status(this.state.statusFilters, value.response.status);
        })
    };

    handleChange = (event) => {
        this.setState({
            search: event.target.value,
        });
    };

    render() {
        const {source, loading, columns, search} = this.state;

        return (
            <div>
                <Card>
                    <CardHeader source={source} url="/httptrace" refresh={() => this.refresh()}
                                title={<FormattedMessage id={"trace.title"}/>}/>
                    <CardBody loading={loading}>
                        <div className={"filters"}>
                            <Typography component={"span"}>
                                <FormattedMessage id="filter.methods"/>
                                {utils.methods.map((method, idx) => {
                                    return (
                                        <ButtonFilter key={idx} text={method} color={utils.color(method)}
                                                      onSelect={() => this.handleFilter('method', method, true)}
                                                      onDelete={() => this.handleFilter('method', method, false)}/>
                                    );
                                })}
                            </Typography>
                            <Typography component={"span"}>
                                <FormattedMessage id="filter.statuses"/>
                                {utils.statuses.map((status, idx) => {
                                    return (
                                        <ButtonFilter key={idx} text={status} color={utils.color(status)}
                                                      onSelect={() => this.handleFilter('status', status, true)}
                                                      onDelete={() => this.handleFilter('status', status, false)}/>
                                    );
                                })}
                            </Typography>
                            <Input id="search" type={"text"} className={"full-width"} value={search}
                                   onChange={this.handleChange} placeholder={this.searchPlaceHolder()}
                                   endAdornment={
                                       <InputAdornment position="end">
                                           <Icon>search</Icon>
                                       </InputAdornment>
                                   }
                            />
                        </div>
                        {source &&
                        <CardTable
                            data={source.traces} columns={columns} customFilter={this.filter}
                            initialOrder={"desc"} initialOrderBy={"timestamp"}
                            row={(row, idx) => {
                                return (
                                    <TableRow key={idx}>
                                        <TableCell>{row.timestamp}</TableCell>
                                        <TableCell>
                                            <ColoredButton size={"s"}
                                                           color={utils.color(row.response.status)}
                                                           text={row.response.status}>
                                            </ColoredButton>
                                        </TableCell>
                                        <TableCell>{row.timeTaken}</TableCell>
                                        <TableCell>
                                            <ColoredButton size={"s"}
                                                           color={utils.color(row.request.method)}
                                                           text={row.request.method}>
                                            </ColoredButton>
                                        </TableCell>
                                        <TableCell>{row.request.uri}</TableCell>
                                        <TableCell><Raw raw={row}/></TableCell>
                                    </TableRow>
                                )
                            }}/>
                        }
                    </CardBody>
                </Card>
            </div>
        );
    }
}

HttpTrace.propTypes = {
    classes: PropTypes.object.isRequired,
    intl: intlShape.isRequired
};

export default injectIntl(withStyles({...utils.defaultCardContentStyle})(HttpTrace));
